name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: mikroelektronika-glcd-font-creator-portable-${{ github.ref_name }}.zip
    steps:
      - name: installer
        shell: cmd
        run: |
          curl -L -O -J https://download.mikroe.com/setups/additional-software/glcd-font-creator/glcd-font-creator-v120.zip &&^
            7z.exe x glcd-font-creator-v120.zip &&^
            7z.exe x GLCD_Font_Creator.1.20.exe
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            GLCDFontCreator.exe
            GLCDFontCreator.chm
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
